[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "vimath"
version = "0.1.0"

[tool.setuptools]
packages = ["vimath"]

[project.scripts]
vimath = "vimath.main:main"